version: '3'
services:
  minecraft:
    container_name: "Minecraft"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    labels:
      image.description: "Minecraft Server Container"
    volumes:
      - /Users/RyanMBP/Developer/minecraft-server/world:/usr/local/minecraft/world